// <auto-generated />
using System;
using CENS15_V2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CENS15_V2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317225702_EntidadDocenteMateria")]
    partial class EntidadDocenteMateria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CENS15_V2.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CENS15_V2.Models.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<int>("Genero")
                        .HasColumnType("integer");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NumeroDocumento")
                        .IsUnique();

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("CENS15_V2.Models.AlumnoContacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreEmergencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelefonoAlumno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelefonoEmergencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId")
                        .IsUnique();

                    b.ToTable("AlumnoContactos");
                });

            modelBuilder.Entity("CENS15_V2.Models.AlumnoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("integer");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("text");

                    b.Property<bool>("Presentado")
                        .HasColumnType("boolean");

                    b.Property<int>("TipoDocumentoAlumnoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("TipoDocumentoAlumnoId");

                    b.ToTable("AlumnoDocumentos");
                });

            modelBuilder.Entity("CENS15_V2.Models.AlumnoNacimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("integer");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId")
                        .IsUnique();

                    b.ToTable("AlumnoNacimientos");
                });

            modelBuilder.Entity("CENS15_V2.Models.Anexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Anexos");
                });

            modelBuilder.Entity("CENS15_V2.Models.Auth", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Auths");
                });

            modelBuilder.Entity("CENS15_V2.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnexoId")
                        .HasColumnType("integer");

                    b.Property<string>("CursoNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrientacionId")
                        .HasColumnType("integer");

                    b.Property<bool>("Semipresencial")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AnexoId");

                    b.HasIndex("OrientacionId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("CENS15_V2.Models.Docente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("CENS15_V2.Models.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("integer");

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<int>("CursoId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaInscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("AlumnoId", "CursoId", "Anio")
                        .IsUnique();

                    b.ToTable("Inscripciones");
                });

            modelBuilder.Entity("CENS15_V2.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CursoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CursoId", "Nombre")
                        .IsUnique();

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("CENS15_V2.Models.MateriaDocente", b =>
                {
                    b.Property<int>("MateriaId")
                        .HasColumnType("integer");

                    b.Property<int>("DocenteId")
                        .HasColumnType("integer");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MateriaId", "DocenteId");

                    b.HasIndex("DocenteId");

                    b.HasIndex("MateriaId", "Rol")
                        .IsUnique();

                    b.ToTable("MateriaDocentes");
                });

            modelBuilder.Entity("CENS15_V2.Models.Orientacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreCorto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("NombreCorto")
                        .IsUnique();

                    b.ToTable("Orientaciones");
                });

            modelBuilder.Entity("CENS15_V2.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("CENS15_V2.Models.Responsibility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Responsibilities");
                });

            modelBuilder.Entity("CENS15_V2.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CENS15_V2.Models.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermission");
                });

            modelBuilder.Entity("CENS15_V2.Models.RoleResponsibility", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResponsibilityId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "ResponsibilityId");

                    b.HasIndex("ResponsibilityId");

                    b.ToTable("RoleResponsibility");
                });

            modelBuilder.Entity("CENS15_V2.Models.TipoDocumentoAlumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposDocumentoAlumno");
                });

            modelBuilder.Entity("CENS15_V2.Models.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("CENS15_V2.Entities.User", b =>
                {
                    b.HasOne("CENS15_V2.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CENS15_V2.Models.AlumnoContacto", b =>
                {
                    b.HasOne("CENS15_V2.Models.Alumno", "Alumno")
                        .WithOne("Contacto")
                        .HasForeignKey("CENS15_V2.Models.AlumnoContacto", "AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");
                });

            modelBuilder.Entity("CENS15_V2.Models.AlumnoDocumento", b =>
                {
                    b.HasOne("CENS15_V2.Models.Alumno", "Alumno")
                        .WithMany("Documentos")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CENS15_V2.Models.TipoDocumentoAlumno", "TipoDocumentoAlumno")
                        .WithMany("Documentos")
                        .HasForeignKey("TipoDocumentoAlumnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("TipoDocumentoAlumno");
                });

            modelBuilder.Entity("CENS15_V2.Models.AlumnoNacimiento", b =>
                {
                    b.HasOne("CENS15_V2.Models.Alumno", "Alumno")
                        .WithOne("DatosNacimiento")
                        .HasForeignKey("CENS15_V2.Models.AlumnoNacimiento", "AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");
                });

            modelBuilder.Entity("CENS15_V2.Models.Auth", b =>
                {
                    b.HasOne("CENS15_V2.Entities.User", "User")
                        .WithOne("Auth")
                        .HasForeignKey("CENS15_V2.Models.Auth", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CENS15_V2.Models.Curso", b =>
                {
                    b.HasOne("CENS15_V2.Models.Anexo", "Anexo")
                        .WithMany("Cursos")
                        .HasForeignKey("AnexoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CENS15_V2.Models.Orientacion", "Orientacion")
                        .WithMany("Cursos")
                        .HasForeignKey("OrientacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anexo");

                    b.Navigation("Orientacion");
                });

            modelBuilder.Entity("CENS15_V2.Models.Docente", b =>
                {
                    b.HasOne("CENS15_V2.Entities.User", "User")
                        .WithOne("Docente")
                        .HasForeignKey("CENS15_V2.Models.Docente", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("CENS15_V2.Models.Inscripcion", b =>
                {
                    b.HasOne("CENS15_V2.Models.Alumno", "Alumno")
                        .WithMany("Inscripciones")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CENS15_V2.Models.Curso", "Curso")
                        .WithMany("Inscripciones")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("CENS15_V2.Models.Materia", b =>
                {
                    b.HasOne("CENS15_V2.Models.Curso", "Curso")
                        .WithMany("Materias")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("CENS15_V2.Models.MateriaDocente", b =>
                {
                    b.HasOne("CENS15_V2.Models.Docente", "Docente")
                        .WithMany("Materias")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CENS15_V2.Models.Materia", "Materia")
                        .WithMany("Docentes")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docente");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("CENS15_V2.Models.RolePermission", b =>
                {
                    b.HasOne("CENS15_V2.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CENS15_V2.Models.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CENS15_V2.Models.RoleResponsibility", b =>
                {
                    b.HasOne("CENS15_V2.Models.Responsibility", "Responsibility")
                        .WithMany("Roles")
                        .HasForeignKey("ResponsibilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CENS15_V2.Models.Role", "Role")
                        .WithMany("Responsibilities")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Responsibility");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CENS15_V2.Models.Token", b =>
                {
                    b.HasOne("CENS15_V2.Models.Auth", "Auth")
                        .WithOne("Token")
                        .HasForeignKey("CENS15_V2.Models.Token", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auth");
                });

            modelBuilder.Entity("CENS15_V2.Entities.User", b =>
                {
                    b.Navigation("Auth")
                        .IsRequired();

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("CENS15_V2.Models.Alumno", b =>
                {
                    b.Navigation("Contacto")
                        .IsRequired();

                    b.Navigation("DatosNacimiento")
                        .IsRequired();

                    b.Navigation("Documentos");

                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("CENS15_V2.Models.Anexo", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("CENS15_V2.Models.Auth", b =>
                {
                    b.Navigation("Token")
                        .IsRequired();
                });

            modelBuilder.Entity("CENS15_V2.Models.Curso", b =>
                {
                    b.Navigation("Inscripciones");

                    b.Navigation("Materias");
                });

            modelBuilder.Entity("CENS15_V2.Models.Docente", b =>
                {
                    b.Navigation("Materias");
                });

            modelBuilder.Entity("CENS15_V2.Models.Materia", b =>
                {
                    b.Navigation("Docentes");
                });

            modelBuilder.Entity("CENS15_V2.Models.Orientacion", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("CENS15_V2.Models.Responsibility", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("CENS15_V2.Models.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Responsibilities");
                });

            modelBuilder.Entity("CENS15_V2.Models.TipoDocumentoAlumno", b =>
                {
                    b.Navigation("Documentos");
                });
#pragma warning restore 612, 618
        }
    }
}
