using CENS15_V2.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CENS15_V2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617002000_AddLoginActivities")]
    public partial class AddLoginActivities : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""LoginActivities"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""Email"" text NOT NULL,
                    ""UserId"" uuid NULL,
                    ""Success"" boolean NOT NULL,
                    ""Reason"" text NULL,
                    ""Platform"" text NULL,
                    ""DeviceInfo"" text NULL,
                    ""AppVersion"" text NULL,
                    ""IpAddress"" text NULL,
                    CONSTRAINT ""FK_LoginActivities_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users"" (""Id"") ON DELETE SET NULL
                );
            ");

            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_LoginActivities_CreatedAt"" ON ""LoginActivities"" (""CreatedAt"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_LoginActivities_Email"" ON ""LoginActivities"" (""Email"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_LoginActivities_UserId"" ON ""LoginActivities"" (""UserId"");");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""LoginActivities"";");
        }
    }
}
