using CENS15_V2.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CENS15_V2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617003000_AddPasswordResetCodes")]
    public partial class AddPasswordResetCodes : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""PasswordResetCodes"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""AuthId"" uuid NOT NULL,
                    ""CodeHash"" text NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""ExpiresAt"" timestamp with time zone NOT NULL,
                    ""UsedAt"" timestamp with time zone NULL,
                    ""Attempts"" integer NOT NULL,
                    CONSTRAINT ""FK_PasswordResetCodes_Auths_AuthId"" FOREIGN KEY (""AuthId"") REFERENCES ""Auths"" (""Id"") ON DELETE CASCADE
                );
            ");

            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_PasswordResetCodes_AuthId"" ON ""PasswordResetCodes"" (""AuthId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_PasswordResetCodes_ExpiresAt"" ON ""PasswordResetCodes"" (""ExpiresAt"");");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""PasswordResetCodes"";");
        }
    }
}
